### ISSUE TITLE
linking with `link.exe` failed: exit code: 1181

### ISSUE THREAD

**Issue by vae520283995** [KZen-networks/kms-secp256k1#25]
I try to run ecdsa/two_Party/test.rs prompt
error: linking with `link.exe` failed: exit code: 1181
note: LINK : fatal error LNK1181: cannot open input file 'gmp.lib'

**Comment by omershlo** [comment]
Hi, 
please install gmp on your machine: https://gmplib.org/manual/Installing-GMP.html

**Comment by vae520283995** [comment]
I have installed GMP and reported an error

E:\kms-secp256k1\kms-secp256k1-master\src\ecdsa\two_party>cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.27s
     Running E:\kms-secp256k1\kms-secp256k1-master\target\debug\deps\kms-e1caa7c4fa199225.exe
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `E:\kms-secp256k1\kms-secp256k1-master\target\debug\deps\kms-e1caa7c4fa199225.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)

**Comment by omershlo** [comment]
thanks for reporting this. 
It seems that you are running on windows OS? 
If this is the case I must say that the code was never tested on Windows (only Mac/Linux). I don't have Windows available at the moment but your are more than welcome to open an issue and we will look into it.

**Comment by vae520283995** [comment]
> 感谢您举报。
> 看来您正在Windows OS上运行？
> 如果是这种情况，我必须说该代码从未在Windows（仅Mac / Linux）上进行过测试。我目前没有Windows，但非常欢迎您提出问题，我们将进行调查。

Yes, I am running on Windows 10
Do you have any communication groups? I'm very interested in MPC

**Comment by omershlo** [comment]
yes! please join our telegram: https://t.me/kzen_research

**Comment by vae520283995** [comment]
Thank you very much for vhnatyk's help
Summarize how I solved it:
You need to install 32-bit MSVC first
This is the command:  rustup install nightly-i686-pc-windows-msvc
Then get gmp.lib and gmp.dll from  https://github.com/vhnatyk/gmp-release
Copy to C:\Users\xxx\.rustup\toolchains\nightly-i686-pc-windows-msvc\lib\rustlib\i686-pc-windows-msvc\lib
It's that simple
